apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brain-app
  template:
    metadata:
      labels:
        app: brain-app
    spec:
      containers:
      - name: mindtrack
        image: 634747715945.dkr.ecr.ap-south-1.amazonaws.com/mindtrack-repo:latest
        ports:
        - containerPort: 80
